# Generated by Django 5.1.6 on 2025-02-24 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0)),
                ('num_tests', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_score', '-average_score'],
            },
        ),
    ]
